export const REDIRECT_FROM_LANDING_PAGE_TIME = 1500;
export const FILES_PER_SAMPLE = 5;
export const POLLING_INTERVAL = 5000; // 5 secs
export const HOME_POLLING_INTERVAL = 60000; // 1 mins

export const REPORT_FETCHING = 'REPORT_FETCHING';
export const REPORT_FETCHED = 'REPORT_FETCHED';
export const RECENT_EXPERIMENTS_FETCHING = 'RECENT_EXPERIMENTS_FETCHING';
export const RECENT_EXPERIMENTS_FETCHED = 'RECENT_EXPERIMENTS_FETCHED';

export const SELECTED_EXPERIMENT_DTO = 'SELECTED_EXPERIMENT_DTO';
export const SELECTED_EXPERIMENT = 'SELECTED_EXPERIMENT';
export const SELECTED_EXPERIMENT_UPDATE = 'SELECTED_EXPERIMENT_UPDATE';
export const RERENDER_MAIN_EXP = 'RERENDER_MAIN_EXP';
